### ISSUE TITLE
config.yaml help

### ISSUE THREAD

**Issue by jyjohnson** [Appdynamics/aws-rds-monitoring-extension#1]
Hi - can you help me with the config file? Say I have 2 RDS instances "db1-prod" and "db2-prod". How do I configure the config file to capture CPUUtilization for both?

Thanks.

**Comment by akshayAppd** [comment]
config.yml  comes with includeDBIdentifiers flag to provide all identifiers which need to be filtered.

#Filters metrics based on DB identifier names provided. Accepts regex patterns
includeDBIdentifiers: ["demodb"]
